export const examSubjects = [
  'English Language',
  'Mathematics',
  'Biology',
  'Chemistry',
  'Physics',
  'Agricultural Science',
  'Economics',
  'Geography',
  'Civic Education',
  'Government',
  'Commerce',
  'Financial Accounting',
  'Literature in English',
  'Christian Religious Studies',
  'Islamic Religious Studies',
  'Technical Drawing',
  'Further Mathematics',
  'History',
  'French',
  'Computer Studies',
];